// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TotemPWA.Data;

#nullable disable

namespace TotemPWA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Burgers",
                            Slug = "burgers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Combos",
                            Slug = "combos"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bebidas",
                            Slug = "bebidas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Acompanhamentos",
                            Slug = "acompanhamentos"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Molhos",
                            Slug = "molhos"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Artesanais",
                            ParentCategoryId = 1,
                            Slug = "artesanais"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tradicionais",
                            ParentCategoryId = 1,
                            Slug = "tradicionais"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Refrigerantes",
                            ParentCategoryId = 3,
                            Slug = "refrigerantes"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sucos",
                            ParentCategoryId = 3,
                            Slug = "sucos"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Batatas",
                            ParentCategoryId = 4,
                            Slug = "batatas"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Onion Rings",
                            ParentCategoryId = 4,
                            Slug = "onion-rings"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Combos Premium",
                            ParentCategoryId = 2,
                            Slug = "combos-premium"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Combos Familiares",
                            ParentCategoryId = 2,
                            Slug = "combos-familiares"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Molhos Picantes",
                            ParentCategoryId = 5,
                            Slug = "molhos-picantes"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Molhos Especiais",
                            ParentCategoryId = 5,
                            Slug = "molhos-especiais"
                        });
                });

            modelBuilder.Entity("TotemPWA.Models.Composition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IngredientId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoAdicional")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("IngredientId1");

                    b.HasIndex("ProductId");

                    b.ToTable("Compositions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            MaxQuantity = 1,
                            Nome = "",
                            PrecoAdicional = 0m,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 2,
                            MaxQuantity = 1,
                            Nome = "",
                            PrecoAdicional = 0m,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 3,
                            MaxQuantity = 1,
                            Nome = "",
                            PrecoAdicional = 0m,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 4,
                            MaxQuantity = 1,
                            Nome = "",
                            PrecoAdicional = 0m,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 5,
                            MaxQuantity = 1,
                            Nome = "",
                            PrecoAdicional = 0m,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("TotemPWA.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalPrice = 2.00m,
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 2,
                            AdditionalPrice = 1.50m,
                            Name = "Queijo Extra"
                        },
                        new
                        {
                            Id = 3,
                            AdditionalPrice = 1.00m,
                            Name = "Ovo"
                        },
                        new
                        {
                            Id = 4,
                            AdditionalPrice = 1.20m,
                            Name = "Cebola Caramelizada"
                        },
                        new
                        {
                            Id = 5,
                            AdditionalPrice = 0.80m,
                            Name = "Pimenta Jalapeño"
                        });
                });

            modelBuilder.Entity("TotemPWA.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            Description = "Pão brioche, blend artesanal, queijo cheddar",
                            Foto = "burguerI.jpg",
                            Name = "Cheeseburger Artesanal",
                            Price = 18.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 6,
                            Description = "Pão australiano, bacon crocante, cheddar derretido",
                            Foto = "burguerII.jpg",
                            Name = "Bacon Cheddar",
                            Price = 21.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            Description = "Pão de parmesão, carne 180g, molho blue cheese",
                            Foto = "burguerIII.jpg",
                            Name = "Blue Cheese Burger",
                            Price = 22.50m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            Description = "Pão pretzel, trufas, queijo gruyère",
                            Foto = "buguer404.png",
                            Name = "Truffle Burger",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Description = "Pão integral, hambúrguer de grão-de-bico",
                            Foto = "veggie.jpg",
                            Name = "Veggie Artesanal",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            Description = "Pão, carne, queijo e molho especial",
                            Foto = "veggie.jpg",
                            Name = "Cheeseburger Clássico",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Pão, carne, queijo, presunto e salada",
                            Foto = "veggie.jpg",
                            Name = "X-Burger",
                            Price = 16.50m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            Description = "Pão, carne, queijo, bacon e salada",
                            Foto = "veggie.jpg",
                            Name = "X-Bacon",
                            Price = 18.50m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            Description = "Pão, carne, queijo, ovo e salada",
                            Foto = "veggie.jpg",
                            Name = "X-Egg",
                            Price = 17.50m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 7,
                            Description = "Pão, 2 carnes, queijo, bacon, ovo e salada",
                            Foto = "veggie.jpg",
                            Name = "X-Tudo",
                            Price = 20.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 8,
                            Description = "350ml",
                            Foto = "coca.webp",
                            Name = "Coca-Cola Lata",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 8,
                            Description = "350ml",
                            Foto = "gurana.jpg",
                            Name = "Guaraná Antarctica",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            Description = "350ml",
                            Foto = "Fanta-Laranja.webp",
                            Name = "Fanta Laranja",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 8,
                            Description = "350ml",
                            Foto = "sprite.webp",
                            Name = "Sprite",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            Description = "Garrafa 600ml",
                            Foto = "coca600.webp",
                            Name = "Coca-Cola 600ml",
                            Price = 8.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 9,
                            Description = "Natural 500ml",
                            Foto = "coca.webp",
                            Name = "Suco de Laranja",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            Description = "Natural 500ml",
                            Foto = "coca.webp",
                            Name = "Suco de Abacaxi",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            Description = "Natural 500ml",
                            Foto = "coca.webp",
                            Name = "Suco de Morango",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 9,
                            Description = "Natural 500ml",
                            Foto = "coca.webp",
                            Name = "Suco de Maracujá",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 9,
                            Description = "Couve, abacaxi e gengibre 500ml",
                            Foto = "coca.webp",
                            Name = "Suco Verde",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 10,
                            Description = "Porção pequena",
                            Foto = "batata frita.jpg",
                            Name = "Batata Frita Pequena",
                            Price = 8.00m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 10,
                            Description = "Porção média",
                            Foto = "batata frita.jpg",
                            Name = "Batata Frita Média",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 10,
                            Description = "Porção grande",
                            Foto = "batata frita.jpg",
                            Name = "Batata Frita Grande",
                            Price = 16.00m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 10,
                            Description = "Porção média com cheddar e bacon",
                            Foto = "batata frita.jpg",
                            Name = "Batata Cheddar e Bacon",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 10,
                            Description = "Porção média de batata doce",
                            Foto = "batatadoce.webp",
                            Name = "Batata Doce",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 11,
                            Description = "Porção pequena",
                            Foto = "batata frita.jpg",
                            Name = "Onion Rings Pequena",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 11,
                            Description = "Porção média",
                            Foto = "batata frita.jpg",
                            Name = "Onion Rings Média",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 11,
                            Description = "Porção grande",
                            Foto = "batata frita.jpg",
                            Name = "Onion Rings Grande",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 11,
                            Description = "Porção média com cheddar",
                            Foto = "batata frita.jpg",
                            Name = "Onion Rings Cheddar",
                            Price = 16.00m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 11,
                            Description = "Porção média com molho picante",
                            Foto = "batata frita.jpg",
                            Name = "Onion Rings Picante",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 12,
                            Description = "Truffle Burger + Batata Grande + Bebida Premium",
                            Foto = "ComboCapa.png",
                            Name = "Combo Truffle",
                            Price = 45.99m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 12,
                            Description = "Bacon Cheddar + Onion Rings Grande + Suco Natural",
                            Foto = "CombosTransparente.png",
                            Name = "Combo Gourmet",
                            Price = 42.50m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 12,
                            Description = "Veggie Artesanal + Batata Doce + Suco Verde",
                            Foto = "ComboCapa.png",
                            Name = "Combo Veggie",
                            Price = 38.99m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 12,
                            Description = "Blue Cheese Burger + Batata Cheddar + Vinho",
                            Foto = "CombosTransparente.png",
                            Name = "Combo Blue Cheese",
                            Price = 43.50m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 12,
                            Description = "Artesanal + Batata Média + Refri 600ml",
                            Foto = "ComboCapa.png",
                            Name = "Combo Executivo",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 13,
                            Description = "4 Burgers + 2 Batatas Grandes + 4 Bebidas",
                            Foto = "CombosTransparente.png",
                            Name = "Combo Família 4 Pessoas",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 13,
                            Description = "6 Burgers + 3 Batatas Grandes + 6 Bebidas + Molhos",
                            Foto = "ComboCapa.png",
                            Name = "Combo Festa",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 13,
                            Description = "2 Burgers Kids + Batata Pequena + 2 Sucos",
                            Foto = "ComboCapa.png",
                            Name = "Combo Kids",
                            Price = 65.00m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 13,
                            Description = "2 Burgers + Batata Média + 2 Bebidas",
                            Foto = "CombosTransparente.png",
                            Name = "Combo Casal",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 13,
                            Description = "3 Burgers + 2 Batatas Médias + 3 Bebidas",
                            Foto = "ComboCapa.png",
                            Name = "Combo Economia",
                            Price = 75.50m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 14,
                            Description = "50ml - Picância média",
                            Foto = "pimenta1.jpg",
                            Name = "Molho de Pimenta Jalapeño",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 14,
                            Description = "50ml - Picância forte",
                            Foto = "pimenta2.jpg",
                            Name = "Molho Habanero",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 14,
                            Description = "50ml - Picância média",
                            Foto = "pimenta3.jpg",
                            Name = "Molho de Pimenta Caiena",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 14,
                            Description = "50ml - Picância suave com sabor defumado",
                            Foto = "pimenta4.jpg",
                            Name = "Molho Chipotle",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 14,
                            Description = "50ml - Extremamente picante",
                            Foto = "pimenta1.jpg",
                            Name = "Molho Inferno",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 15,
                            Description = "50ml - Sofisticado com toque de trufas",
                            Foto = "pimenta2.jpg",
                            Name = "Molho Trufado",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 15,
                            Description = "50ml - Blend de 3 queijos",
                            Foto = "pimenta3.jpg",
                            Name = "Molho de Queijos",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 15,
                            Description = "50ml - Barbecue com whisky bourbon",
                            Foto = "pimenta4.jpg",
                            Name = "Molho Barbecue Bourbon",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 15,
                            Description = "50ml - Exclusivo alho fermentado",
                            Foto = "pimenta2.jpg",
                            Name = "Molho de Alho Negro",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 15,
                            Description = "50ml - Clássico molho caesar",
                            Foto = "pimenta1.jpg",
                            Name = "Molho Caesar",
                            Price = 4.50m
                        });
                });

            modelBuilder.Entity("TotemPWA.Models.Variation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Variation", (string)null);
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.HasOne("Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("TotemPWA.Models.Composition", b =>
                {
                    b.HasOne("TotemPWA.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TotemPWA.Models.Ingredient", null)
                        .WithMany("Compositions")
                        .HasForeignKey("IngredientId1");

                    b.HasOne("TotemPWA.Models.Product", "Product")
                        .WithMany("Compositions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TotemPWA.Models.Product", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TotemPWA.Models.Variation", b =>
                {
                    b.HasOne("TotemPWA.Models.Product", "Product")
                        .WithMany("Variations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("TotemPWA.Models.Ingredient", b =>
                {
                    b.Navigation("Compositions");
                });

            modelBuilder.Entity("TotemPWA.Models.Product", b =>
                {
                    b.Navigation("Compositions");

                    b.Navigation("Variations");
                });
#pragma warning restore 612, 618
        }
    }
}
